categories = {

    "Đồng Quê" : {
        'Ruộng lúa': 'Rice fields',
        'Ao cá': 'Fish pond',
        'Nhà nông': 'Farmhouse',
        'Cánh đồng hoa': 'Flower field',
        'Dốc đồng cỏ': 'Grassy hill',
        'Bến thuyền': 'Boat dock',
        'Cổ thụ': 'Ancient tree',
        'Nhà gạch': 'Brick house',
        'Lối đi nhỏ': 'Narrow pathway',
        'Ngôi làng': 'Village',
        'Gia đình nông dân': 'Farm family',
        'Cánh đồng ngô': 'Cornfield',
        'Đồi cỏ xanh': 'Green hill',
        'Đồng cỏ bát ngát': 'Expansive grassland',
        'Nhà mái ngói': 'Tile-roofed house',
        'Cổng làng': 'Village gate',
        'Quê hương': 'Homeland',
        'Đàn gia cầm': 'Poultry flock',
        'Ngôi nhà tranh': 'Thatched house',
        'Nhà nông truyền thống': 'Traditional farmhouse'
    },

    "Phong Cảnh" : {
        'Bãi biển': 'Beach',
        'Núi non': 'Mountains',
        'Thác nước': 'Waterfall',
        'Rừng cây': 'Forest',
        'Hồ nước': 'Lake',
        'Sông suối': 'River',
        'Thảo nguyên': 'Prairie',
        'Sa mạc': 'Desert',
        'Đồng cỏ': 'Meadow',
        'Đồng ruộng': 'Farmland',
        'Ao hồ': 'Pond',
        'Khu vườn': 'Garden',
        'Khu rừng thông': 'Pine forest',
        'Đảo hoang': 'Deserted island',
        'Thung lũng': 'Valley',
        'Bờ hồ': 'Lakeside',
        'Bãi cỏ xanh': 'Green field',
        'Đô thị': 'Urban area',
        'Công viên': 'Park area'
    },

    "Biển" : {
        'Bãi biển': 'Beach',
        'Đá dưới nước': 'Underwater rocks',
        'Rạn san hô': 'Coral reef',
        'Ngọn đèn biển': 'Lighthouse',
        'Nước biển sâu': 'Deep sea',
        'Ngọn hải đăng': 'Cliff',
        'Sóng biển': 'Ocean waves',
        'Nhà ven biển': 'Beach house',
        'Chài cá': 'Fishing net',
        'Tàu cá': 'Fishing boat',
        'Sao biển': 'Starfish',
        'Bờ cát trắng': 'White sand',
        'Ngư dân': 'Fisherman',
        'Người lướt sóng': 'Surfer',
    },


    "Thành Phố" : {
        'Công viên': 'Park',
        'Nhà cao tầng': 'Skyscraper',
        'Người đi bộ': 'Pedestrian flow',
        'Bến xe bus': 'Bus station',
        'Quảng trường': 'Square',
        'Tòa nhà văn phòng': 'Office building',
        'Nhà hàng phố': 'Street-side cafe',
        'Bệnh viện' : 'Hospital',
        'Đèn đường': 'Street lights',
        'Ga tàu điện': 'Subway station',
        'Khu mua sắm': 'Shopping district',
        'Dòng xe cộ': 'Traffic flow',
        'Trung tâm mua sắm': 'Shopping center',
        'Đèn neon': 'Neon lights'
    },

    "Trường Lớp" : {
        'Phòng học': 'Classroom',
        'Bảng đen': 'Blackboard',
        'Bảng trắng': 'Whiteboard',
        'Bàn học': 'Desk',
        'Ghế học': 'Chair',
        'Bảng phấn màu': 'Chalkboard',
        'Giáo viên': 'Teacher',
        'Học sinh': 'Student',
        'Sách giáo trình': 'Textbook',
        'Thư viện': 'Library',
        'Sân trường': 'Schoolyard',
        'Cổng trường': 'School gate',
        'Bảng thông báo': 'Bulletin board',
        'Phòng thực hành': 'Laboratory'
    },

    "Đáy Biển" : {
        'Rạn san hô': 'Coral reef',
        'Thủy cung': 'Aquarium',
        'Cá mập': 'Shark',
        'Hòn đảo dưới nước': 'Underwater island',
        'Tảo biển': 'Seaweed',
        'Ngọc trai': 'Pearl',
        'Đá ngầm': 'Underwater rocks',
        'Đồng cỏ biển': 'Seagrass',
        'Conch': 'Conch shell',
        'Sò điệp': 'Clam',
        'Ngọc bích': 'Jade',
        'Hải quỳ': 'Sea anemone',
        'Xà cừ': 'Mother of pearl',
        'Cá heo': 'Dolphin',
        'Động vật biển': 'Marine life',
        'Cá hồi': 'Salmon',
        'Sao biển': 'Starfish',
        'Cua' : 'Crab',
    },

    "Rừng Rậm" :{
        'Rừng cây cao': 'Tall trees forest',
        'Dòng sông trong rừng': 'River in the forest',
        'Rừng thông': 'Pine forest',
        'Rừng mưa nhiệt đới': 'Tropical rainforest',
        'Ngọn núi': 'Mountain',
        'Thác nước': 'Waterfall',
        'Ngôi nhà gỗ': 'Wooden house ',
        'Rừng sồi': 'Oak forest',
        'Thạch nhũ đỏ': 'Red moss',
        'Hồ nước': 'Forest lake',
        'Rừng thông trắng': 'White pine forest',
        'Thảo nguyên rừng': 'Forest meadow',
        'Con đường rừng': 'Forest path',
        'Cây cổ thụ': 'Ancient trees',
        'Động vật': 'Forest wildlife',
        'Chim chóc': 'Birds',
    },

    "Lễ Hội" : {
        'Pháo hoa': 'Fireworks',
        'Đèn lồng': 'Lanterns',
        'Máy bay phun nước': 'Water plane',
        'Mặt nạ': 'Mask',
        'Nhảy múa dân gian': 'Folk dance',
        'Ăn uống đường phố': 'Street food',
        'Dàn nhạc di động': 'Mobile music band',
        'Đám rước đèn hoa': 'Light parade',
        'Vũ điệu truyền thống': 'Traditional dance',
        'Điều hòa khí trời': 'Climate control',
        'Đối diện ảo': 'Virtual reality',
        'Biểu diễn nghệ thuật đương đại': 'Contemporary art performance',
        'Gian hàng nghệ thuật': 'Art stalls',
        'Cuộc thi hát': 'Singing contest',
        'Trò chơi và giải đố': 'Games and puzzles',
        'Triển lãm nghệ thuật': 'Art exhibition',
        'Cảm biến âm thanh': 'Sound sensor',
        'Hội chợ đêm': 'Night market',
        'Dạ tiệc ngoại ô': 'Outdoor banquet',
        'Đêm nhạc phố': 'Street music night'
    },

    "Ẩm thực Việt Nam" : {
        'Phở' : "Phở",
        'Bánh mì': 'Vietnamese banh mi',
        'Gỏi cuốn': 'Spring rolls',
        'Bánh xèo': 'Sizzling pancake',
        'Bánh tráng trộn': 'Mixed rice paper',
        'Cá kho tộ': 'Caramelized fish',
        'Gà nướng': 'Honey grilled chicken',
        'Bò lúc lắc': 'Shaking beef',
        'Bánh gối': 'Pillow cake',
        'Bánh bèo': 'Water fern cake',
        'Bánh flan': 'Creme caramel',
        'Bánh tráng nướng': 'Grilled rice paper',
        'Bánh bao': 'Steamed bun',
        'Chả giờ' : 'Crispy Spring Rolls',
        'Cơm chiên' : 'Fried rice',
    },
    
    "Món ăn" : {
        'Phở': 'Pho',
        'Sushi': 'Sushi',
        'Pizza': 'Pizza',
        'Paella': 'Paella',
        'Mì Ý': 'Spaghetti',
        'Croissant': 'Croissant',
        'Bánh Taco': 'Taco',
        'Dim Sum': 'Dim Sum',
        'Pad Thai': 'Pad Thai',
        'Kimchi': 'Kimchi',
        'Mì Ramen': 'Ramen',
        'Bít tết': 'Beefsteak',
        'Hamburger': 'Hamburger',
        'Khoai tây chiên' : 'French fries',
        'Cơm chiên' : 'Fried rice',
        'Gà rán' : 'Chicken fried',
        'Bánh Hot Dog' : "Hot Dog",
        'Sandwich' : 'Sandwich',
        'Trái cây ': 'Fruits dish',
        'Salad': 'Salad',
    },
    "Thức Ăn Nhanh" : {
        'Hamburger': 'Hamburger',
        'Bánh mì sandwich': 'Sandwich',
        'Bánh Pizza': 'Pizza',
        'Bánh Hotdog': 'Hotdog',
        'Khoai tây chiên': 'French fries',
        'Gà rán': 'Fried chicken',
        'Gà viên' : 'Chicken balls',
        'Coca' : 'Coke',
        'Nước cam' : 'Orange juice',
        '7up' : '7-Up',
        'Salad' : 'Salad',
        'Khoai tây nghiền' : 'Mashed potato',
    }
    
}