categories = {

    "Đồng Quê" : {
        'Ruộng lúa': 'Rice fields',
        'Ao cá': 'Fish pond',
        'Nhà nông': 'Farmhouse',
        'Cánh đồng hoa': 'Flower field',
        'Dốc đồng cỏ': 'Grassy hill',
        'Bến thuyền': 'Boat dock',
        'Cổ thụ': 'Ancient tree',
        'Nhà gạch': 'Brick house',
        'Lối đi nhỏ': 'Narrow pathway',
        'Ngôi làng': 'Village',
        'Gia đình nông dân': 'Farm family',
        'Cánh đồng ngô': 'Cornfield',
        'Đồi cỏ xanh': 'Green hill',
        'Đồng cỏ bát ngát': 'Expansive grassland',
        'Nhà mái ngói': 'Tile-roofed house',
        'Cổng làng': 'Village gate',
        'Quê hương': 'Homeland',
        'Đàn gia cầm': 'Poultry flock',
        'Ngôi nhà tranh': 'Thatched house',
        'Nhà nông truyền thống': 'Traditional farmhouse'
    },

    "Phong Cảnh" : {
        'Bãi biển': 'Beach',
        'Núi non': 'Mountains',
        'Thác nước': 'Waterfall',
        'Rừng cây': 'Forest',
        'Hồ nước': 'Lake',
        'Sông suối': 'River',
        'Thảo nguyên': 'Prairie',
        'Sa mạc': 'Desert',
        'Đồng cỏ': 'Meadow',
        'Đồng ruộng': 'Farmland',
        'Ao hồ': 'Pond',
        'Khu vườn': 'Garden',
        'Khu rừng thông': 'Pine forest',
        'Đảo hoang': 'Deserted island',
        'Thung lũng': 'Valley',
        'Bờ hồ': 'Lakeside',
        'Bãi cỏ xanh': 'Green field',
        'Đô thị': 'Urban area',
        'Công viên': 'Park area'
    },



    "Động Vật" : {
        'Chó': 'Dog',
        'Mèo': 'Cat',
        'Vịt': 'Duck',
        'Gà': 'Chicken',
        'Heo': 'Pig',
        'Ngựa': 'Horse',
        'Gấu': 'Bear',
        'Hổ': 'Tiger',
        'Sư tử': 'Lion',
        'Khỉ': 'Monkey',
        'Cá voi': 'Whale',
        'Cá ngựa': 'Seahorse',
        'Rùa': 'Turtle',
        'Chuột': 'Mouse',
        'Chim én': 'Swallow',
        'Voi': 'Elephant',
        'Cáo': 'Fox',
        'Hươu cao cổ': 'Giraffe',
        'Cá heo': 'Dolphin',
        'Cá mập': 'Shark',
    },

    "Biển" : {
        'Bãi biển': 'Beach',
        'Đá dưới nước': 'Underwater rocks',
        'Rạn san hô': 'Coral reef',
        'Ngọn đèn biển': 'Lighthouse',
        'Nước biển sâu': 'Deep sea',
        'Ngọn hải đăng': 'Cliff',
        'Sóng biển': 'Ocean waves',
        'Nhà ven biển': 'Beach house',
        'Chài cá': 'Fishing net',
        'Tàu cá': 'Fishing boat',
        'Sao biển': 'Starfish',
        'Bờ cát trắng': 'White sand',
        'Ngư dân': 'Fisherman',
        'Người lướt sóng': 'Surfer',
    },


    "Thành Phố" : {
        'Công viên': 'Park',
        'Nhà cao tầng': 'Skyscraper',
        'Người đi bộ': 'Pedestrian flow',
        'Bến xe bus': 'Bus station',
        'Quảng trường': 'Square',
        'Tòa nhà văn phòng': 'Office building',
        'Nhà hàng phố': 'Street-side cafe',
        'Bệnh viện' : 'Hospital',
        'Đèn đường': 'Street lights',
        'Ga tàu điện': 'Subway station',
        'Khu mua sắm': 'Shopping district',
        'Dòng xe cộ': 'Traffic flow',
        'Trung tâm mua sắm': 'Shopping center',
        'Đèn neon': 'Neon lights'
    },

    "Trường Lớp" : {
        'Phòng học': 'Classroom',
        'Bảng đen': 'Blackboard',
        'Bảng trắng': 'Whiteboard',
        'Bàn học': 'Desk',
        'Ghế học': 'Chair',
        'Bảng phấn màu': 'Chalkboard',
        'Giáo viên': 'Teacher',
        'Học sinh': 'Student',
        'Sách giáo trình': 'Textbook',
        'Thư viện': 'Library',
        'Sân trường': 'Schoolyard',
        'Cổng trường': 'School gate',
        'Bảng thông báo': 'Bulletin board',
        'Phòng thực hành': 'Laboratory'
    },

}